export const CaloriesConstants = [
  {
    labelName: '< 50 calories',
    type: 'radio',
    name: 'calories',
    value: '< 50',
    ariaLabel: '50 or less calories',
  },
  {
    labelName: '50 - 100 calories',
    type: 'radio',
    name: 'calories',
    value: '50-100',
    ariaLabel: '50 to 100 calories',
  },
  {
    labelName: '100 - 200 calories',
    type: 'radio',
    name: 'calories',
    value: '100-200',
    ariaLabel: '100 to 200 calories',
  },
  {
    labelName: '200 - 300 calories',
    type: 'radio',
    name: 'calories',
    value: '200-300',
    ariaLabel: '200 to 300 calories',
  },
  {
    labelName: '300 - 400 calories',
    type: 'radio',
    name: 'calories',
    value: '300-400',
    ariaLabel: '300 to 400 calories',
  },
  {
    labelName: '400 - 500 calories',
    type: 'radio',
    name: 'calories',
    value: '400-500',
    ariaLabel: '400 to 500 calories',
  },
  {
    labelName: '> 500 calories',
    type: 'radio',
    name: 'calories',
    value: '500+',
    ariaLabel: '500 or more calories',
  },
];
export const DietConstants = [
  {
    labelName: 'Balanced',
    type: 'checkbox',
    name: 'dietType',
    value: 'balanced',
    ariaLabel: 'Balanced Diet',
  },
  {
    labelName: 'High Fiber',
    type: 'checkbox',
    name: 'dietType',
    value: 'high-fiber',
    ariaLabel: 'High Fiber Diet',
  },
  {
    labelName: 'High Protein',
    type: 'checkbox',
    name: 'dietType',
    value: 'high-protein',
    ariaLabel: 'High Protein Diet',
  },
  {
    labelName: 'Low Carb',
    type: 'checkbox',
    name: 'dietType',
    value: 'low-carb',
    ariaLabel: 'Low Carb Diet',
  },
  {
    labelName: 'Low Fat',
    type: 'checkbox',
    name: 'dietType',
    value: 'low-fat',
    ariaLabel: 'Low Fat Diet',
  },
  {
    labelName: 'Low Sodium',
    type: 'checkbox',
    name: 'dietType',
    value: 'low-sodium',
    ariaLabel: 'Low Sodium Diet',
  },
];

export const HealthConstants = [
  {
    labelName: 'Alcohol Cocktail',
    type: 'checkbox',
    name: 'health',
    value: 'alcohol-cocktail',
    ariaLabel: 'Alcohol Cocktail',
  },
  {
    labelName: 'Alcohol Free',
    type: 'checkbox',
    name: 'health',
    value: 'alcohol-free',
    ariaLabel: 'Alcohol-Free',
  },
  {
    labelName: 'Celery Free',
    type: 'checkbox',
    name: 'health',
    value: 'celery-free',
    ariaLabel: 'Celery-Free',
  },
  {
    labelName: 'Crustacean Free',
    type: 'checkbox',
    name: 'health',
    value: 'crustacean-free',
    ariaLabel: 'Crustacean-Free',
  },
  {
    labelName: 'Dairy Free',
    type: 'checkbox',
    name: 'health',
    value: 'dairy-free',
    ariaLabel: 'Dairy-Free',
  },
  {
    labelName: 'DASH',
    type: 'checkbox',
    name: 'health',
    value: 'DASH',
    ariaLabel: 'DASH Diet',
  },
  {
    labelName: 'Egg Free',
    type: 'checkbox',
    name: 'health',
    value: 'egg-free',
    ariaLabel: 'Egg-Free',
  },
  {
    labelName: 'Fish Free',
    type: 'checkbox',
    name: 'health',
    value: 'fish-free',
    ariaLabel: 'Fish-Free',
  },
  {
    labelName: 'FODMAP Free',
    type: 'checkbox',
    name: 'health',
    value: 'FODMAP-free',
    ariaLabel: 'FODMAP-Free',
  },
  {
    labelName: 'Gluten Free',
    type: 'checkbox',
    name: 'health',
    value: 'gluten-free',
    ariaLabel: 'Gluten-Free',
  },
  {
    labelName: 'Immuno Supportive',
    type: 'checkbox',
    name: 'health',
    value: 'immuno-supportive',
    ariaLabel: 'Immuno Supportive',
  },
  {
    labelName: 'Keto Friendly',
    type: 'checkbox',
    name: 'health',
    value: 'keto-friendly',
    ariaLabel: 'Keto Friendly',
  },
]